# Generated by Django 3.1.4 on 2021-01-19 17:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.RichTextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Образец документа',
                'verbose_name_plural': 'Образец документа',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SamplesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Все образцы документов',
            },
            bases=('wagtailcore.page',),
        ),
    ]
