# Generated by Django 3.1.6 on 2021-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conspage',
            name='too_old',
            field=models.BooleanField(default=False),
        ),
    ]
