# Generated by Django 3.1.6 on 2021-02-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cons', '0002_conspage_too_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conspage',
            name='too_old',
            field=models.BooleanField(default=False, verbose_name='Устарела'),
        ),
    ]
