# Generated by Django 3.1.6 on 2021-02-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('cons', '0005_conspage_too_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='conspage',
            name='previous_cons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
