# Generated by Django 3.1.6 on 2021-02-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('cons', '0007_auto_20210208_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedConsOrderable',
            new_name='PreviousConsOrderable',
        ),
    ]
