# Generated by Django 3.1.6 on 2021-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210217_1058'),
        ('cons', '0012_auto_20210218_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='conspage',
            name='authors',
            field=models.ManyToManyField(related_name='cons', to='base.Author'),
        ),
        migrations.DeleteModel(
            name='ConsAuthor',
        ),
    ]
