# Generated by Django 3.1.6 on 2021-02-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210217_1058'),
        ('cons', '0015_auto_20210218_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conspage',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='conss', to='base.Author'),
        ),
    ]
