# Generated by Django 3.1.6 on 2021-02-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cons', '0018_auto_20210218_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conspage',
            old_name='main_client',
            new_name='client_preview',
        ),
        migrations.RenameField(
            model_name='conspage',
            old_name='main_question',
            new_name='question_preview',
        ),
    ]
