# Generated by Django 3.1.6 on 2021-02-19 07:51

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210218_1810'),
        ('cons', '0019_auto_20210218_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conspage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(to='base.Author'),
        ),
    ]
