# Generated by Django 3.1.6 on 2021-02-19 07:59

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210218_1810'),
        ('cons', '0020_auto_20210219_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conspage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='base.Author'),
        ),
    ]
