# Generated by Django 3.1.6 on 2021-02-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cons', '0021_auto_20210219_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conspage',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
    ]
