# Generated by Django 3.1.6 on 2021-02-19 14:34

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cons', '0023_auto_20210219_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cons.FAQPageTag', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
