# Generated by Django 3.1.6 on 2021-02-19 16:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_auto_20210219_0933'),
        ('cons', '0024_auto_20210219_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Задать вопрос',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
    ]
