# Generated by Django 3.1.4 on 2021-01-20 10:03

import base.blocks
from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', base.blocks.RichtextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, help_text='Содержание', null=True),
        ),
    ]
