# Generated by Django 3.1.6 on 2021-02-05 17:24

import base.blocks
from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticlepage',
            name='subtitle',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', base.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Таблица'))], blank=True, help_text='Содержание', null=True),
        ),
    ]
