# Generated by Django 3.1.6 on 2021-02-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210205_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='content',
            new_name='description',
        ),
    ]
