# Generated by Django 3.1.6 on 2021-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210205_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
