# Generated by Django 3.1.6 on 2021-02-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogindexpage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
