# Generated by Django 3.1.6 on 2021-02-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210223_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
