# Generated by Django 3.1.6 on 2021-02-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210217_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='surname',
        ),
    ]
