# Generated by Django 3.1.6 on 2021-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210217_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='short_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия + инициалы'),
        ),
    ]
