# Generated by Django 3.1.6 on 2021-02-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210217_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, default='hand-help.ru', null=True, verbose_name='Страница'),
        ),
    ]
