# Generated by Django 3.1.6 on 2021-02-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210217_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='short_name',
        ),
        migrations.AddField(
            model_name='author',
            name='alias',
            field=models.CharField(max_length=50, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='author',
            name='midlle_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='author',
            name='profession',
            field=models.CharField(max_length=200, null=True, verbose_name='Профессия/Звание/...'),
        ),
        migrations.AddField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
