# Generated by Django 3.1.6 on 2021-02-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210217_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='midlle_name',
            new_name='middle_name',
        ),
    ]
