# Generated by Django 3.1.6 on 2021-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210217_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Профессия/Звание/...'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
