# Generated by Django 3.1.6 on 2021-02-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210217_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='website',
            new_name='page_url',
        ),
    ]
