# Generated by Django 3.1.6 on 2021-02-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_auto_20210219_0933'),
        ('base', '0011_auto_20210220_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='page_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='Страница на hand-help'),
        ),
        migrations.AlterField(
            model_name='author',
            name='website_url',
            field=models.URLField(blank=True, default='hand-help.ru', null=True, verbose_name='Страница на стороннем сайте'),
        ),
    ]
