# Generated by Django 3.1.6 on 2021-02-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Страница новостей', 'verbose_name_plural': 'Страницы новостей'},
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='date',
        ),
        migrations.DeleteModel(
            name='NewsIndexPage',
        ),
    ]
