# Generated by Django 3.1.4 on 2021-01-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsindexpage',
            options={'verbose_name': 'Страница всех новостей', 'verbose_name_plural': 'Страницы всех новостей'},
        ),
    ]
