# Generated by Django 3.1.6 on 2021-02-05 13:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=wagtail.core.fields.StreamField([('news_item', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(label='Дата', required=True)), ('text', wagtail.core.blocks.RichTextBlock(label='Текст', required=True))]))], null=True),
        ),
    ]
