# Generated by Django 3.1.6 on 2021-02-05 17:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210205_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Страница новостей'},
        ),
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=wagtail.core.fields.StreamField([('news_item', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(label='Дата', required=True)), ('text', wagtail.core.blocks.RichTextBlock(label='Текст', required=True))]))], blank=True, null=True),
        ),
    ]
