# Generated by Django 3.1.6 on 2021-02-07 08:06

import base.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210205_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=wagtail.core.fields.StreamField([('news_item', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(label='Дата', required=True)), ('text', base.blocks.RichTextBlock(label='Текст', required=True))]))], blank=True, null=True),
        ),
    ]
