# Generated by Django 3.1.6 on 2021-02-03 13:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('text_sign', wagtail.core.fields.RichTextField(blank=True, max_length=250, verbose_name='Подпись')),
                ('ads', wagtail.core.fields.StreamField([('ad', wagtail.core.blocks.RichTextBlock(help_text='Объявление', label='Объявление'))], blank=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
    ]
