# Generated by Django 3.1.6 on 2021-02-01 18:46

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ads',
            field=wagtail.core.fields.StreamField([('ad', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_sign',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
