# Generated by Django 3.1.6 on 2021-02-01 18:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210201_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text_sign',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=250),
        ),
    ]
