# Generated by Django 3.1.6 on 2021-02-01 19:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210201_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='ads',
            field=wagtail.core.fields.StreamField([('ad', wagtail.core.blocks.RichTextBlock(help_text='Объявление'))], blank=True),
        ),
    ]
