# Generated by Django 3.1.6 on 2021-02-01 19:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210201_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='ads',
            field=wagtail.core.fields.StreamField([('ad', wagtail.core.blocks.RichTextBlock(help_text='Объявление', label='Объявление'))], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_sign',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=250, verbose_name='Подпись'),
        ),
    ]
