# Generated by Django 3.1.6 on 2021-02-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationpage2tag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='consultationpage2tag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ConsultationPage2',
        ),
        migrations.DeleteModel(
            name='ConsultationPage2Tag',
        ),
    ]
