# Generated by Django 3.1.6 on 2021-02-02 08:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_auto_20210202_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationsindexpage',
            name='content',
        ),
        migrations.AddField(
            model_name='consultationsindexpage',
            name='ads',
            field=wagtail.core.fields.StreamField([('ad', wagtail.core.blocks.RichTextBlock(help_text='Объявление', label='Объявление'))], blank=True),
        ),
        migrations.AddField(
            model_name='consultationsindexpage',
            name='last_consults_note',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='О режиме публикации'),
        ),
        migrations.AddField(
            model_name='consultationsindexpage',
            name='note',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Примечание'),
        ),
    ]
