# Generated by Django 3.1.6 on 2021-02-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('consultations', '0003_auto_20210202_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsindexpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
